[package]
name = "bit-bots-derive"
version = "0.1.0"
authors = ["Jonathan Spira <jjspira@gmail.com>"]
edition = "2018"

[dependencies]
quote = "1.0"
syn = "1.0"
heck = "0.3.1"

[lib]
proc-macro = true